config/routes.rb
Rails.application.routes.draw do
  
  resources :products
  root 'pages#home'
  get '/home', to: 'pages#home'

  get 'hello/:name', to: 'pages#hello', as: 'hello'

  get '/about', to: 'pages#about'
  
  get '/contact' => 'pages#contact'

  get '/index', to: 'posts#index'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html



end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :commentable, polymorphic: true
end

app/models/course.rb
class Course < ApplicationRecord
    has_and_belongs_to_many :users
    has_many :comments, as: :commentable
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :user
    validates :title, :body, :published, presence: true
    has_many :comments, as: :commentable
    # validates :category, format: {with: /\A[a-zA-Z]+\z/, message: "only allows letters" }  
    # validates :published, inclusion: { in: [true, false] }


    scope :published, -> { where(published: true)}

    before_create :fill_body, :mark_as_published


    def fill_body
        self.body = 'This is a Post'
    end

    def mark_as_published
        published = true
    end
end

app/models/product.rb
class Product < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
    has_many :posts
    has_and_belongs_to_many :courses
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  layout "login_layout", only: [:about]


  def home
  end


  def hello
    @name = params[:name]
  end


  #About us
  def about
    @name = "Jhon"
  end


  #contact
  def contact
    @address = "Calle 2B #81A - 380"
    @email = "jhonarmont@hotmail.com"
  end

  # Posts 



end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def index
    @products = Product.all
  end

  def show
    @product = Product.find(params[:id])
  end

  def new
    @product = Product.new
  end

  def create

    @product = Product.new(product_params)
    if @product.save
      redirect_to products_path
    else
      render :new
    end
  end

  def edit

    @product = Product.find(params[:id])

  end

  def update
    @product = Product.find(params[:id])
    if @product.update(product_params)
      redirect_to products_path
    else
      render :edit
    end
  end
  
  def destroy
    product = Product.find(params[:id])
    product.destroy
    redirect_to products_path
  end

  private

  def product_params

    params.require(:product).permit(:name,
      :description, :price)

    end
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/product_helper.rb
module ProductHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u"
      crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.2.0/css/all.css" integrity="sha384-hWVjflwFxL6sNzntih27bfxkr27PmbbK/iSvJ+a4+0owXq79v+lsFkW54bOGbiDQ" crossorigin="anonymous">
    <title>RailsBlog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <style>
      body {
        padding-top: 70px;
      }

      ul {
        list-style: none;
      }
    </style>

  </head>

  <body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1"
          aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/"><i class="far fa-image"></i> PhotoGallery</a>
      </div>
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <li> <%= link_to "Home", home_path %> </li>
          <li> <%= link_to "Post", index_path %> </li>
          <li> <%= link_to "About Us", about_path %></li>
          <li> <%= link_to "Contact", contact_path %> <li>
          <li> <%= link_to "Hello", hello_url('Jhon Arias')%></li>
          <li> <%= link_to "Products", products_path %> <li>
        </ul> 
        <ul class="nav navbar-nav navbar-right">
          <li> <a href="#"><i class="fas fa-user-plus"></i> Sign up</a> </li>
          <li> <a href="#"><i class="fas fa-sign-in-alt"></i> Login</a> </li>
        </ul>
      </div>
    </div>
  </nav>
  
  <div class="container">

    <% flash.each do |name, msg|  %>
      <%=content_tag :div, msg, class: name %>
    <% end%>
    <%= yield %>

  </div>

  </body>
</html>

app/views/layouts/login_layout.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>PhotoGallery!</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" type="text/css" media="screen" href="main.css" />

  <style>
 html, body { 
   
   width: 100%; height: 100%; 
 
 }
.bg-img { position: relative; width: 100%; height: 100%; background: url('http://unsplash.it/1200x800')
center center no-repeat; background-size: cover;

 &:before { content: ''; position: absolute; top: 0; right: 0; bottom: 0;
left: 0; background-image: linear-gradient(to bottom right, #002f4b, #dc4225); opacity: .6;

 }
  }
  </style>


</head>
<body>
<div class="bg-img"></div>


 <div class="container">

  <%= yield %>

 </div>
</body>
</html>

app/views/pages/about.html.erb
<h1>About us</h1>
<h3>Hi <%= @name %></h3>
<p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Incidunt, repudiandae est nobis minus voluptatem numquam corrupti aspernatur similique, optio accusamus sequi hic dignissimos impedit! Reprehenderit nemo rerum ipsum voluptatibus dolorum.</p>

app/views/pages/contact.html.erb
<h1>Contact us at any time here: </h1>
<ul>
    <li>Address: <%= @address %></li>
    <li>Email: <%= @email %></li>
</ul>

app/views/pages/hello.html.erb
<h1>welcome <%= @name %></h1>

app/views/pages/home.html.erb
<h1>Pages#home(Jhon Arias)</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/posts/index.html.erb
<div class="jumbotron">
    <h1>Hello, you can post your picture here!</h1>
    <div class="container">
        <div class="row">            
            <ul>
                <% @posts.each do |post|%>
                    <div class="col col-md-4">
                        <li><h3><i class="fas fa-cannabis"></i> <%= post.title %> </h3></li>
                        <p><%= post.body %></li></p>
                    </div>
                <% end %>    
            </ul>
        </div>
    </div>
</div> 

app/views/products/_form.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-4 col-md-offset-4">
      <div class="panel panel-default">
        <div class="panel-body">  
          <%= form_for product do |f| %>
    
            <div <div class="form-group">
              <%= f.label :name %><br>
              <%= f.text_field :name %>
            </div>
            <div <div class="form-group">
              <%= f.label :description %><br>
              <%= f.text_area :description %>
            </div>
             <div <div class="form-group">
              <%= f.label :price %><br>
              <%= f.number_field :price %>
            </div>
    
            <div <div class="form-group">
              <%= f.submit "Enviar", class:"btn btn-primary" %>
            </div>
          <% end %>
      
        </div>
      </div>
    </div>
  </div>
</div>

app/views/products/edit.html.erb
<%= render 'form', product: @product, action: 'edit'%>

app/views/products/index.html.erb
<h1>Productos</h1>
<table class="table table-hover table-condensed table-bordered">
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Price</th>
      <th>Options</th>
    </tr>
  </thead>
  <tbody>
    <% @products.each do |product| %>
      <tr class="success">
        <td><%= product.name %></td>
        <td><%= product.description %></td>
        <td><%= product.price %></td>
        <td>
          <%= link_to "Mostrar", product %>
          <%= link_to "Editar", edit_product_path(product) %>
          <%= link_to "Eliminar", product, method: :delete, data: { confirm: "¿Estás seguro de eliminar este producto?" } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= link_to "New product", new_product_path, class:"btn btn-primary"%>

app/views/products/new.html.erb
<%= render 'form', product: @product, action: 'new'%>